captainVersion: 4
services:
    $$cap_appname-db:        
        image: mariadb:$$cap_mariadb_version
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: $$cap_db_pass
            MYSQL_DATABASE: filerun
            MYSQL_USER: filerun
            MYSQL_PASSWORD: $$cap_db_pass            
        volumes:
            - $$cap_appname-db-data:/var/lib/mysql
        caproverExtra:
            notExposeAsWebApp: 'true'
    $$cap_appname:
        image: filerun/filerun:$$cap_filerun_version
        volumes:
            - $$cap_appname-html:/var/www/html
            - $$cap_appname-userfiles:/user-files
        restart: always
        depends_on:
            - $$cap_appname-db
        environment:
            FR_DB_HOST: srv-captain--$$cap_appname-db
            FR_DB_PORT: 3306
            FR_DB_NAME: filerun
            FR_DB_USER: filerun
            FR_DB_PASS: $$cap_db_pass
            APACHE_RUN_USER: www-data
            APACHE_RUN_USER_ID: 33
            APACHE_RUN_GROUP: www-data
            APACHE_RUN_GROUP_ID: 33
caproverOneClickApp:
    variables:
        - id: $$cap_filerun_version
          label: Filerun Version.
          defaultValue: 'latest'
          description: Use 'latest' tag for normal installation. Check out their Docker page for the valid tags https://hub.docker.com/r/filerun/filerun/tags
          validRegex: /^([^\s^\/])+$/    
        - id: $$cap_mariadb_version
          label: MariaDB (database) version
          defaultValue: 10.1
          description: Check out their Docker page for the valid tags https://hub.docker.com/_/mariadb?tab=tags
          validRegex: /^([^\s^\/])+$/
        - id: $$cap_db_pass
          label: Database password for user named 'filerun'
          description: ''
          validRegex: /.{1,}/

    instructions:
        start: >-
            FileRun is a self-hosted Google Drive alternative. It is a full featured web based file manager with an easy to use user interface. It is great for managing your photo, movie, audio collection, or sharing files with your family and friends.

            Enter your Database Configuration parameters and click on next. A FileRun container will be created for you. The process will take about a minute for the process to finish. 
            
        end: >-
            FileRun is deployed and available as $$cap_appname-wordpress. 

            Username: superuser  Password: superuser

            IMPORTANT: It will take up to 2 minutes for FileRun to be ready. Before that, you might see a 502 error page.

            Remember that this app will not create a Database by itself. You need to provide all that information.
    displayName: FileRun
    isOfficial: true
    description: FileRun is a self-hosted Google Drive alternative. It is a full featured web based file manager with an easy to use user interface.
    documentation: Taken from https://docs.filerun.com/docker.
